---
title: "Tidy_dplyr"
author: "wuyijin"
date: "2019年2月13日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*   dplyr是 R 語言中最常被用來進行資料轉換的套件，內建許多與 SQL 相似的函數，幫助我們在 R 中完成資料轉換。
    *   dplyr 套件有幾個好處：
        *   提供以「動詞」為命名的函數，讓你能夠直接將想達成的資料轉換翻譯成程式碼
        *   提供資料轉換的「標準化框架」，有系統的思考你需要做的資料轉換
        *   在效能上有優化，較其他套件的函數快
    ```{r warning=FALSE}
    # install.packages("tidyverse")
    library(dplyr) 
    library(ggplot2) # diamonds 
    
    diamonds.tb <- as_tibble(diamonds)
    diamonds.tb
    ```
    *   filter():Row 的篩選
    ```{r warning=FALSE}
    diamonds.tb %>%
      filter(cut == "Ideal")
    
    ## 使用變數標記。注意:filter_()，字串標記符號。
    Col <- 'cut'
    Val <- 'Ideal'
    diamonds.tb %>%
      filter_(sprintf("%s == '%s'",Col,Val))
    
    diamonds.tb %>%
      filter(cut %in% c("Ideal","Good")) # 篩選出 cut column 值 "Ideal" 與 "Good"(值有大小寫之分) 
    
    diamonds.tb %>%
      filter(carat < 0.3 | carat > 5) # 篩選出 carat column 值介於 0.3 ~ 5 之間    
    ```
    
    *   slice():抓指定筆數資料
    ```{r warning=FALSE}
    mtcars.tb <- as_tibble(mtcars)
    mtcars.tb
    
    mtcars.tb %>%
      slice(1:4) # 抓取前4筆資料
    
    mtcars.tb %>%
      slice(-4) # 移除前4筆資料
    
    mtcars.tb %>%
      slice(c(1:3,9)) # 抓前3筆資料與第9筆資料
    ``` 
    
    *   select():Column 的篩選    
    ```{r warning=FALSE}
    mtcars.tb %>%
      select(mpg, hp, gear) # 選出「一加侖汽油可跑距離」、「馬力」、與「前進檔數」三個 column
    
    mtcars.tb %>%
      select(-mpg) # 排除 mpg column
    
    mtcars.tb %>%
      select(starts_with('d')) # column name d 開頭
    
    diamonds.tb %>%
      select(ends_with('t'))  # column name t 結尾
    
    diamonds.tb %>%
      select(contains('a')) # column name 包含 a
    
    mtcars.tb %>%
      filter(mpg > 20, hp >100) %>% # 篩選出一加侖汽油的可以跑超過 20 km 且馬力超過 100 匹馬力汽車的「前進檔數」
      select(gear)
    ``` 

    *   arrange():資料排序。asc(default)、desc    
    ```{r warning=FALSE}
    mtcars.tb %>%
      arrange(cyl, disp) # 依 cyl、disp 排序
    
    mtcars.tb %>%
      arrange(desc(disp)) # 依 disp 做降冪排序
    ```    
    
    *   mutate():建立新的變數    
    ```{r warning=FALSE}
    mtcars.tb %>%
      mutate(cyl2 = cyl * 2, cyl4 = cyl2 * 2)
    ```   
    
    *   mutate():建立新的變數    
    ```{r warning=FALSE}
    mtcars.tb %>%
      mutate(cyl2 = cyl * 2, cyl4 = cyl2 * 2)
    
    mtcars.tb %>%
      mutate(mpg = NULL, disp = disp * 0.0163871)
    ``` 
    *   transmute():只保留建立 new column    
    ```{r warning=FALSE}
    mtcars.tb %>%
      transmute(displ_l = disp / 61.0237)
    ``` 
    
    *   group_by():根據組別加總    
    ```{r warning=FALSE}
    mtcars.tb %>%
      group_by(cyl)
    
    mtcars.tb %>%
      group_by(cyl) %>%
      filter(rank(desc(hp)) < 4) %>% 
      arrange(desc(cyl),desc(hp))    # 依 cy1 分組，篩選 hp 排名降冪前3名，依 cy1、hp 做降冪排列
    ```    

    *   summarise():分組後的資料總結    
    ```{r warning=FALSE}
    mtcars.tb %>%
      group_by(cyl) %>%
      summarise(number=n(),avg_hp=mean(hp),sd_hp=sd(hp),max_hp=max(hp),min_hp=min(hp)) %>%
      arrange(desc(avg_hp))  
    ```    